[tool.poetry]
name = "msdlpack"
version = "0.1.0"
description = ""
authors = ["songjhaha <songjh96@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
mindspore = "^1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
